### ISSUE TITLE
How to report issues?

### ISSUE THREAD

**Issue by yoogx** [Fabien-Chouteau/setup-ada#5]
Hi,

I use this action on my own repository here:
https://github.com/OpenAADL/ocarina/runs/1401540078?check_suite_focus=true

and got a crash. How can I report bugs from the main repo?
https://github.com/ada-actions/toolchain does not allow issue

Thanks

**Comment by Fabien-Chouteau** [comment]
Hi @yoogx , I opened the issue section.
